apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-api-configmap
  namespace: fiap-cloud-games
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://+:8080
  RabbitMq__Host: rabbitmq
  RabbitMq__Port: "5672"
  RabbitMq__VirtualHost: /
  PaymentSimulation__DefaultStatus: Approved
